### ISSUE TITLE
Archiving 

### ISSUE THREAD

**Issue by Geoo15** [IanMitchell/deschtimes#34]
Would be nice to be able to archive projects and staff positions instead of deleting them.

![Screenshot 08_15_2021 02_10_38](https://user-images.githubusercontent.com/65097182/129462376-b9a3c72b-be39-4ba3-bc38-1219578246a9.png)

**Comment by IanMitchell** [comment]
What would archiving do? I usually see people just leave the show as-is in a finished state

**Comment by Geoo15** [comment]
> What would archiving do? I usually see people just leave the show as-is in a finished state

Let's say you drop a show or delay it and if you ever wanted to continue where you left off in the future you would need to recreate the show and mark all the positions as complete again if you removed it. Archiving would allow people to well.. archive the show leaving it the way it is, then, if in the future you decide to give it a shot again you could un-archive the show and resume from the state you left it in. 

For example, the [are-we-there-yet](https://github.com/GrygrFlzr/are-we-there-yet) website embed. Piling 20+ shows you aren't even working on isn't too appealing to the common eye, and deleting the show is just a pain in the ass to re-create, it messes with Aquarius' Discord updates and everything.

**Comment by IanMitchell** [comment]
If you toggle the show to hide it, it should stop appearing there - I think I'd recommend doing that instead of an archive. Little hesitant to add another show state into the codebase

**Comment by Geoo15** [comment]
Works for me. Thanks
